general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# 30seg -> Screen falling gamma
listener {
    timeout = 30
    on-timeout = ddcutil setvcp 10 10
    on-resume = sleep 0.1 && ddcutil setvcp 10 100
}

# 60seg -> Screen lock
listener {
    timeout = 60
    on-timeout = loginctl lock-session
}

# 5min -> Screen shutdown
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && ddcutil setvcp 10 100
}

# 30min -> Suspend PC
listener {
    timeout = 1800
    on-timeout = systemctl suspend
    on-resume = sleep 0.1 && ddcutil setvcp 10 100
}

