general {
    # avoid starting multiple hyprlock instances.
    lock_cmd = pidof hyprlock || hyprlock

    # lock before suspend.
    before_sleep_cmd = loginctl lock-session

    # to avoid having to press a key twice to turn on the display.
    after_sleep_cmd = hyprctl dispatch dpms on
}


#-------------------------------------------------------------------------------
# -> Screen falling gamma
#-------------------------------------------------------------------------------
listener {
    # 30seg
    timeout = 30

    # Setting gamma(10) to 10%
    on-timeout = ddcutil setvcp 10 10

    # Wait, and setting gamma(10) to 100%
    on-resume = sleep 0.1 && ddcutil setvcp 10 100
}


#-------------------------------------------------------------------------------
# -> Screen lock
#-------------------------------------------------------------------------------
listener {
    # 5min
    timeout = 300

    # Call lock-session command
    on-timeout = loginctl lock-session
}


#-------------------------------------------------------------------------------
# -> Screen shutdown
#-------------------------------------------------------------------------------
listener {
    # 10min
    timeout = 600

    # Turning off screen
    on-timeout = hyprctl dispatch dpms off

    # Wake screen, and setting gamma(10) to 100%
    on-resume = hyprctl dispatch dpms on && ddcutil setvcp 10 100
}


#-------------------------------------------------------------------------------
# -> Suspend PC
#-------------------------------------------------------------------------------
listener {
    # 30min
    timeout = 1800

    # Suspend computer
    on-timeout = systemctl suspend

    # Wait, and setting gamma(10) to 100%
    on-resume = sleep 0.1 && ddcutil setvcp 10 100
}

